export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const CHANGE_QUANTITY_CART = 'CHANGE_QUANTITY_CART';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const RESET_HOME_PAGE = 'RESET_HOME_PAGE';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
