export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const INCREASE_QUANTITY_CART = 'INCREASE_QUANTITY_CART';
export const DECREASE_QUANTITY_CART = 'DECREASE_QUANTITY_CART';
